version : 2 
sources:
  - name: gz
    schema: gz_raw_data
    tables: 
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
      - name: product
        identifier: raw_gz_product
        description: product of Greenweez / we have on row per products_id 
        columns:
          - name: products_id
            tests:
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweez / we have on row per order_id 
        columns:
          - name: orders_id
            tests:
              - unique
      - name: adwords
        identifier: raw_gz_adwords
        description: camp of adwors
        columns:
          - name: date_date
            tests:
              - unique
              - not_null
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
      - name: int_campaingns
        description: union all des toutes les campagnes (adwors, criteo, bing & facebook)
      - name: int_campaigns_day
        description: int_campaingns grouper par date du jour
          
